#!/bin/bash 

# Colores
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # Sin color

# Verificar que se ha pasado un argumento
if [ "$#" -ne 2 ]; then
    echo -e "${RED}[Error]${NC} Uso: $0 <INTERFAZ> <RED_OBJETIVO>"
    echo -e "${BLUE}Ejemplo:${NC} $0 eth0 192.168.180.0"
    exit 1
fi

INTERFACE=$1
TARGET_NETWORK=$2

# Obtener la IP de la interfaz especificada
IP=$(ifconfig | grep "$INTERFACE" -A1 | grep inet | awk '{print $2}')

if [ -z "$IP" ]; then
    echo -e "${RED}[Error]${NC} No se pudo obtener la IP de la interfaz $INTERFACE."
    exit 1
fi

# Obtener la red de la IP
SUBNET=$(echo "$IP" | awk -F'.' '{print $1"."$2"."$3".0/24"}')

# Habilitar reenvío de IP
echo -e "${GREEN}[+]${NC} Habilitando el reenvío de IP..."
sudo sh -c 'echo 1 > /proc/sys/net/ipv4/ip_forward'

# Configuración de iptables
echo -e "${GREEN}[+]${NC} Configurando reglas de iptables..."

# Regla para permitir el tráfico establecido y relacionado
sudo iptables -A FORWARD -i tun0 -o "$INTERFACE" -m state --state RELATED,ESTABLISHED -j ACCEPT
# Regla para permitir el tráfico desde $INTERFACE hacia tun0
sudo iptables -A FORWARD -i "$INTERFACE" -o tun0 -j ACCEPT
# Regla para enmascarar el tráfico desde la subred calculada
sudo iptables -t nat -A POSTROUTING -s "$SUBNET" -o tun0 -j MASQUERADE

# Instrucciones para la máquina Windows
echo -e "\n${BLUE}[+]${NC} Ejecuta en Windows:"
echo -e "${BLUE}\t route add $TARGET_NETWORK mask 255.255.255.0 $IP${NC}"

echo -e "\n${BLUE}[+]${NC} Muestra las tablas de enrutamiento:"
echo -e "${BLUE}\t route print${NC}"

echo -e "\n${BLUE}[+]${NC} Para borrar las reglas de enrutamiento de windows:"
echo -e "${BLUE}\t route delete $TARGET_NETWORK${NC}"

# Instrucciones para limpiar la configuración
echo -e "\n${RED}[+]${NC} Para borrar las reglas de iptables y deshabilitar el reenvío de IP en kali:"
echo -e "${RED}\t sudo iptables -F${NC}"
echo -e "${RED}\t sudo sh -c 'echo 0 > /proc/sys/net/ipv4/ip_forward'${NC}"
